### ISSUE TITLE
Edm.DateTime ATOM format is not parsed correctly

### ISSUE THREAD

**Issue by OmniTroid** [SAP/python-pyodata#202] opened 2022-01-30 16:13 UTC
When execution reaches https://github.com/SAP/python-pyodata/blob/master/pyodata/v2/service.py#L765

It assumes the format is JSON, however the ATOM formatting is still perfectly valid, but the library seemingly has no mechanism to detect if this is the case or not.

So if this library is used against a server that ATOM-formats its Edm.DateTime, the following error happens:

`pyodata.exceptions.PyODataModelError: Malformed value 2022-01-04 for primitive Edm.DateTime type. Expected format is /Date(<ticks>[±<offset>])/`

**Comment by phanak-sap** [comment] 2022-01-31 10:26
Hi @OmniTroid could you please provide test that would reproduce this behavior?

**Comment by squeakyboots** [comment] 2022-05-27 22:45
I have the same error running v1.9.1 of pyodata against an SAP ByDesign tenant's OData service: https://my301795.sapbydesign.com/sap/byd/odata/cust/v1/ablemate/BusinessPartnerCollection?$filter=InternalID eq 'NBS'

The JSON returned:
```
{
	"d": {
		"results": [
			{
				"__metadata": {
					"uri": "https://my301795.sapbydesign.com/sap/byd/odata/cust/v1/ablemate/BusinessPartnerCollection('00163E0265D71ED28ECFF48DDCD64CF2')",
					"type": "cust.BusinessPartner"
				},
				"ObjectID": "00163E0265D71ED28ECFF48DDCD64CF2",
				"InternalID": "NBS",
				"CSM_KUT": "",
				"ProjectManager_KUT": "",
				"Consultant_KUT": "",
				"ServiceLevel_KUT": "",
				"Platform_KUT": "",
				"LifeCycleStatusCode": "2",
				"RegionCode": "UT",
				"CountryCode": "US",
				"RoleCode": "BBP000",
				"LastChangeDateTime": "/Date(1639167537708)/",
				"SupportThroughDate_KUT": null,
				"BusinessPartnerFormattedName": "Navigator Business Solutions",
				"URI": "nbs-us.com"
			}
		]
	}
}
```

I believe it's the "LastChangeDateTime" value causing the error. I recognize it's not ATOM formatted, but it seems to be a similar problem handling date. Let me know if another bug would be appropriate.

**Comment by phanak-sap** [comment] 2022-06-01 10:47
Hi [squeakyboots](https://github.com/squeakyboots) - thanks for thorough bug report and even own investigation + tryout fix.

I believe you have different problem than Omnitroid (at least, there is still no code to reproduce, maybe it is the same, but it mentions return from server in ATOM formatting, not JSON as you did provided). I would prefer you to create a new bug - I am not doing it, since you are referencing it from your project. Just copypaste there your part and I will copypaste there this answer and then delete both in here.

First of all - your edc scanner is great. This is exactly the tool I wanted to build when I will have some spare time :) I need to check into more detail how you solved the odata v4 support.. isn't that something that should be here as well?

Second - please do a PR with your fix and the new tests (and reference the new bug there). If it fixed your problem, it is worth to be upstream.

Third - there are actually a datetime offset tests - but maybe not with the case that reproduces your bug. Refer to this commit (commit message, code changes and new tests), which re-worked the DateTime + DateTimeOffset and maybe you can reproduce the bug with addition of new line to correct parametrized test.
https://github.com/SAP/python-pyodata/commit/ec56995551779cb99ae0a5734a7ecc3449e5191d#diff-7997cda67851c8c96f44d1246b73701adfa2afb643042bf34d11f872c2c5b974

**Comment by phanak-sap** [comment] 2022-09-27 13:22
Based on provided info, this seems like at the moment duplicate of #231. 

@squeakyboots  - I totally forgot about your solution for same problem, it does look better than my ugly adding of "+0000" to the input :)  So reused yours to the master branch.

**Closed by phanak-sap** 2022-09-27 13:22 UTC
Labels: bug

**Comment by phanak-sap** [comment] 2022-09-27 13:23
note for original @OmniTroid  - ATOM is at the moment not supported at all in the pyodata, only the literal and JSONs... but should be, that is for sure.. but that is overall new feature.
