### ISSUE TITLE
need help 

### ISSUE THREAD

**Issue by chinnaphani** [SAP/python-pyodata#23] opened 2019-05-02 02:52 UTC
Hi,

I am getting error as below.

pyodata.exceptions.HttpError: Metadata request failed, status code: 401, body:

**Comment by jfilak** [comment] 2019-05-02 07:45
Is this issue a dupe of the issue #21 ?

**Comment by filak-sap** [comment] 2019-05-06 21:17
Closing this issue as dupe of #21. Thank you for understanding. Feel free to re-open if you disagree.

**Closed by filak-sap** 2019-05-06 21:17 UTC
