### ISSUE TITLE
Authorization header not found

### ISSUE THREAD

**Issue by julzpalomiano** [SAP/python-pyodata#156] opened 2021-06-22 01:07 UTC
Hello, I was trying to login on SAP B1 but I'm always getting an error 'Authorization header not found'. Here is my code

```
import pyodata
import requests

SERVICE_URL=https://192.168.xx.xx:50000/b1s/v1

s = requests.Session()
s.verify = False

 s.post(service_url+'/Login', headers={
            "CompanyDB": SAPDEMO,
            "Password": mypassword,
            "UserName": myusername
        })

client = pyodata.Client(SERVICE_URL, s)
print(client)
```

**Comment by phanak-sap** [comment] 2021-06-25 19:40
Hi @julzpalomiano  - from the code it is not possible to know what happened. 

Try the script the [logging enabled](https://github.com/SAP/python-pyodata/blob/master/docs/usage/advanced.rst#enable-logging).

You can even "go deeper", by enabling logging for the actual http traffic...

>  from http.client import HTTPConnection
>  HTTPConnection.debuglevel = 1
> 
>  logging.basicConfig(format='%(asctime)s %(message)s', datefmt='%m/%d/%Y %I:%M:%S %p')
>  logging.getLogger().setLevel(logging.DEBUG)
>  requests_log = logging.getLogger("requests.packages.urllib3")
>  requests_log.setLevel(logging.DEBUG)
>  requests_log.propagate = True

Hope that helps and the problem is apparent. If not, please post the logging information, so far this issue is neither reproducible nor actionable.

**Comment by julzpalomiano** [comment] 2021-06-26 02:42
Hello @phanak-sap,

I have added your code at the top.

My code:

```
import requests
import urllib3
import datetime
import pyodata
from dotenv import dotenv_values
from http.client import HTTPConnection
import logging
HTTPConnection.debuglevel = 1

logging.basicConfig(format='%(asctime)s %(message)s', datefmt='%m/%d/%Y %I:%M:%S %p')
logging.getLogger().setLevel(logging.DEBUG)
requests_log = logging.getLogger("requests.packages.urllib3")
requests_log.setLevel(logging.DEBUG)
requests_log.propagate = True

config = dotenv_values('.env')

urllib3.disable_warnings()

session = requests.Session()
session.verify = False

session.post(config['SERVICE_URL']+'/Login', headers={
                "CompanyDB": config['SAP_COMPANY_DB'],
                "Password": config['SAP_PASSWORD'],
                "UserName": config['SAP_USERNAME']
            })

client = pyodata.Client(config['SERVICE_URL'], session)

print(client)
```

the result:

```
06/26/2021 10:36:56 AM Starting new HTTPS connection (1): 192.168.18.140:50000
send: b'POST /b1s/v1/Login HTTP/1.1\r\nHost: 192.168.18.140:50000\r\nUser-Agent: python-requests/2.25.1\r\nAccept-Encoding: gzip, deflate\r\nAccept: */*\r\nConnection: keep-alive\r\nCompanyDB: SAPDEMO\r\nPassword: mypassword\r\nUserName: myusername\r\nContent-Length: 0\r\n\r\n'
reply: 'HTTP/1.1 200 OK\r\n'
header: Date: Sat, 26 Jun 2021 02:36:56 GMT
header: Server: Apache
header: DataServiceVersion: 3.0
header: Content-Type: application/json;odata=minimalmetadata;charset=utf-8
header: Set-Cookie: B1SESSION=602215be-d627-11eb-8000-2cea7f9d71a2;HttpOnly;
header: Vary: Accept-Encoding
header: Content-Encoding: gzip
header: Set-Cookie: ROUTEID=.node7; path=/
header: Content-Length: 169
header: Keep-Alive: timeout=5, max=100
header: Connection: Keep-Alive
06/26/2021 10:36:56 AM https://192.168.18.140:50000 "POST /b1s/v1/Login HTTP/1.1" 200 169
Traceback (most recent call last):
  File "C:\Users\Julz\Documents\Julz\PYTHON\TCHUB\pyodata.py", line 4, in <module>
    import pyodata
  File "C:\Users\Julz\Documents\Julz\PYTHON\TCHUB\pyodata.py", line 29, in <module>
    client = pyodata.Client(config['SERVICE_URL'], session)
AttributeError: partially initialized module 'pyodata' has no attribute 'Client' (most likely due to a circular import)
```

any help will be appreciated. Thanks

**Comment by phanak-sap** [comment] 2021-06-26 12:09
Hi @julzpalomiano OK, now we know that it is relevant to metadata parsing and not networking. 

Could you please provide the $metadata XML from your service? Either create your own Gist or you can create PR to the following repository for this particular purpose - https://github.com/phanak-sap/pyodata-issue-files

Also, are you sure it is Odata Version 2 service and not 3/4 (which is not yet supported)?

**Comment by phanak-sap** [comment] 2021-06-26 12:18
Hi @julzpalomiano - this is still not enough to determine if it is problem from networking or metadata parsing. You provided the stack trace  - that one part of the puzzle - but in the console log you should have logs of actual response returned from the server. 

Please check that the response is valid XML document from the $metadata.

A) If not - its hard to investigate not on your computer...You can paste the entire console log with the http request/response logging enabled.. lets see what you see.

B} If yes , then it is not invalid response or networking problem, but trueproblem with parsing of the XML with metadata.

We need the $metadata XML from your service? Either you posted the entire console log - so we know the response now, or you can create your own Gist, or you can create PR to the following repository for this particular purpose - https://github.com/phanak-sap/pyodata-issue-files.

**Comment by julzpalomiano** [comment] 2021-06-26 12:56
Hi @phanak-sap , Thank you for your response. attached the whole console log response.  Please let me know if this is enough. Thank you.

[pyodata_login_response.txt](https://github.com/SAP/python-pyodata/files/6720122/pyodata_login_response.txt)

**Comment by phanak-sap** [comment] 2021-06-26 13:22
OK, valid XML response. that is good from the standpoint that it is easier to reproduce. 
Could you pls attach just the XML file the service $metadata?

**Comment by phanak-sap** [comment] 2021-06-26 13:31
Hi @julzpalomiano - ok, it is valid XML response. Could you anyway pls create PR to the  https://github.com/phanak-sap/pyodata-issue-files with the XML of the  $metadata (you can use the URL https://192.168.xx.xx:50000/b1s/v1$metadata in the browser to see the XML file). Saves the time with the re-formatting/trimming from console output

**Comment by julzpalomiano** [comment] 2021-06-26 14:19
Hi @phanak-sap, I have created a PR already. Thank you for your quick response.

**Comment by phanak-sap** [comment] 2021-06-26 14:37
OK thanks, I didn't read properly the console log but it seems I have found the problem. 

Your $metadata file declares` <edmx:DataServices m:DataServiceVersion="3.0" m:MaxDataServiceVersion="3.0"> which is Odata Version 3. Pyodata so far supports only Odata v2 -support for v4 (together with  v3) is pending; watch https://github.com/SAP/python-pyodata/issues/39

At the moment there is sadly nothing to be done other then implement the other protocol version.

If you are not forced to used python, I can recommend our "sibling" library from nodejs world, https://github.com/SAP/odata-library, which does support odata v1-4.

**Comment by julzpalomiano** [comment] 2021-06-26 15:12
Hi @phanak-sap ,

Ok, I understand. I started my project already. right now I am using the http request like.

`response = requests.get(config['SERVICE_URL']+'/Items', verify=False)`

Thank you for your time looking into my issue :)

**Comment by phanak-sap** [comment] 2021-06-26 15:16
OK, I am closing the issue as essentially dupe of #39

**Closed by phanak-sap** 2021-06-26 15:16 UTC
Labels: V3, duplicate
