### ISSUE TITLE
Query returns valid json but gives an error

### ISSUE THREAD

**Issue by GambitK** [SAP/python-pyodata#74] opened 2019-10-29 21:20 UTC
I'm using pyodata to query a web service and the service responds with a valid Json but I still get an error message on the test script:

```
Traceback (most recent call last):
  File "C:\python\navodata.py", line 30, in <module>
    result = navservice.entity_sets.Customer_Card.get_entity('123456').execute()
  File "C:\Python\Python37-32\lib\site-packages\pyodata\v2\service.py", line 305, in execute
    return self._handler(response)
  File "C:\Python\Python37-32\lib\site-packages\pyodata\v2\service.py", line 1074, in get_entity_handler
    entity = response.json()['d']
KeyError: 'd'
```
Included in the whole debug output.
[output.txt](https://github.com/SAP/python-pyodata/files/3785858/output.txt)

**Comment by filak-sap** [comment] 2019-10-30 00:17
Unfortunately, you use V3 service which is not supported and it's not yet on our roadmap. We are currently working on V4.

**Comment by filak-sap** [comment] 2019-10-30 00:18
Duplicate of #21

**Closed by filak-sap** 2019-10-30 00:18 UTC
Labels: V3
