### ISSUE TITLE
Custom query parameter bug - missing $

### ISSUE THREAD

**Issue by jkminder** [SAP/python-pyodata#216] opened 2022-06-09 12:56 UTC
Adding a custom query parameter to a request does not work because the "$" is not inserted:
`client.entity_sets.BusinessRole.get_entities().top(1).custom("filter", "Language eq 'FR'")   `
should be the same as 
`client.entity_sets.BusinessRole.get_entities().top(1).filter("Language eq 'FR'")   `. 

The urllib logs from the first snipped (custom) clarfiy the problem:
`GET /odata.svc/BusinessRole?filter=Language+eq+%27FR%27&%24top=1`
NOTE the missing "$" (%24) in front of the query param!

If one runs:
`client.entity_sets.BusinessRole.get_entities().top(1).custom("$filter", "Language eq 'FR'")   `
it works properly and the urllib logs state:
`GET /odata.svc/BusinessRole?%24filter=Language+eq+%27FR%27&%24top=1`

**Comment by phanak-sap** [comment] 2022-06-15 20:22
Hi @jkminder,
 I believe this works as designed. "Adding a custom query parameter to a request does not work" sentence is not entirely true, it is IMHO just this edge case of "first and only" query parameter.

1. The documentation is maybe sparse, but [custom](https://github.com/SAP/python-pyodata/blob/master/docs/usage/querying.rst#use-non-standard-odata-url-query-parameters) was added as a possibility to add something after standard odata query parameters. 
2. Is there any reason why you need to run filter query trough `custom` instead of the standard `filter` (same doc page, used in the `get_entities().top(1).filter("Language eq 'FR'")` example)?
3. You were able to create an workaround easily anyway for your scenario anyway, knowing that it is the only query parameter in such code.  If the pyodata would be able to detect that edge case, for what exact purpose? If most of the OData requests will be built using only the `custom` query builder, then IMHO you are in almost similar scenario to building the entire URLs from scratch with just requests library. 

If there is solid use case / explanation to point 2, I am happy to review a PR request from you for such new enhancement (with new tests). Otherwise I am more inclined to close this issue as "works as designed".

**Comment by phanak-sap** [comment] 2022-07-04 05:04
Hi @jkminder,

 before the answer, I have spent anyway quite a time inside a debugger and checking the tests. It was fun, I also learned about requests.PreparedRequest for checking if somehow the URL maybe generated incorrectly (urllib3 is nice, but I wanted to investigate if it is possible to access that inside the  pyodata execute() method). 

The `custom("$skiptoken",...` is really a correct and expected way, as you noted (that you get the desired result, the two code samples from last comment are really different just in the `$` character.). Therefore I see no bug, in both code samples the generated full URL is as expected.

```
client.entity_sets.BusinessRole.get_entities().filter("Language eq 'DE'").custom("$skiptoken", "guid'e3f9d8d3-c36e-4f3b-94fa-00031672b6e1','FR'").top(10).execute()
client.entity_sets.BusinessRole.get_entities().filter("Language eq 'DE'").custom("skiptoken", "guid'e3f9d8d3-c36e-4f3b-94fa-00031672b6e1','FR'").top(10).execute()
```

The `custom` gives you complete control over the url parameters, so it must be a valid, generic URL parameters string. And those begins with `?` and are separated by  `&`.  Some, odata relevant url parameters start with `$`prefix, true, but that does not mean every url parameter in `custom` should have - for example the `sap-client`, noted in documentation is just normal url parameter for SAP gateway, if sometimes needed. 

I am not sure what exactly you mean by `with get_entity it seems to work)` - I have checked that get_entity and get_entities behave exactly the same, in respect to `custom()`:

example:
```
service.entity_sets.MasterEntities.get_entity(1).custom("skiptoken", "guid'e3f9d8d3-c36e-4f3b-94fa-00031672b6e1','FR'")
/MasterEntities('1')?skiptoken=guid%27e3f9d8d3-c36e-4f3b-94fa-00031672b6e1%27%2C%27FR%27
```

And to consider this as a feature request - to maintain special whitelist of parameters that should be automatically added with `$` prefix if they are present inside `custom()` without it - well, that would be completely magic code. Definitely better to leave it to current "developer should know about specifics of what is needed to the URL". 

I will close this issue as "Works as designed/ Not a bug". It must have been an "invalid URL generation" case to be a valid issue. 

But thanks for taking the time for an improvement proposal.

**Comment by jkminder** [comment] 2022-07-04 09:09
Hi thanks for taking time to investigate this. I completely see you point and agree. Not inserting the '$' by default gives one much better control. I think a hint in the docs that, if the url parameter passed into `custom` requires a $ one must provide this. Just in case other people stumble upon this issue.

**Comment by phanak-sap** [comment] 2022-07-04 12:39
Hi @jkminder - true, may be unexpected - feel free to create PR to https://github.com/SAP/python-pyodata/blob/master/docs/usage/querying.rst so it is understandable from a point of view of first glance at this.

**Comment by phanak-sap** [comment] 2022-07-09 13:06
Doc example update in 34a5c33, after merge of new unit tests.

Closing.

**Closed by phanak-sap** 2022-07-09 13:06 UTC
Labels: question, missing_docs
